export const products = [
  {
    id: 1,
    name: "Fresh Cuconut",
    price: "4,600",
    description: "A large phone with one of the best screens",
    img: "../assets/img/products/1.jpg",
  },
  {
    id: 2,
    name: "Fresh Banana",
    price: "3,000",
    description: "A great phone with one of the best cameras",
    img: "../assets/img/products/2.jpg",
  },
  {
    id: 3,
    name: "Farm Pepper",
    price: "10,000",
    description: "A nice phone with everything you need",
    img: "../assets/img/products/3.jpg",
  },
  {
    id: 4,
    name: "Straw Berry",
    price: "1,000",
    description: "A nice phone with everything you need",
    img: "../assets/img/products/4.jpg",
  },
  {
    id: 5,
    name: "Fresh Cuconut",
    price: "4,600",
    description: "A large phone with one of the best screens",
    img: "../assets/img/products/5.jpg",
  },
  {
    id: 6,
    name: "Fresh Banana",
    price: "3,000",
    description: "A great phone with one of the best cameras",
    img: "../assets/img/products/6.jpg",
  },
  {
    id: 7,
    name: "Farm Pepper",
    price: "10,000",
    description: "A nice phone with everything you need",
    img: "../assets/img/products/7.jpg",
  },
  {
    id: 8,
    name: "Straw Berry",
    price: "1,000",
    description: "A nice phone with everything you need",
    img: "../assets/img/products/8.jpg",
  },
  {
    id: 9,
    name: "Fresh Cuconut",
    price: "4,600",
    description: "A large phone with one of the best screens",
    img: "../assets/img/products/13.jpg",
  },
  {
    id: 10,
    name: "Fresh Banana",
    price: "3,000",
    description: "A great phone with one of the best cameras",
    img: "../assets/img/products/10.jpg",
  },
  {
    id: 11,
    name: "Farm Pepper",
    price: "10,000",
    description: "A nice phone with everything you need",
    img: "../assets/img/products/11.jpg",
  },
  {
    id: 12,
    name: "Straw Berry",
    price: "1,000",
    description: "A nice phone with everything you need",
    img: "../assets/img/products/12.jpg",
  },
];
